resize mode finishing up
aws/amazon-ivs-react-native-player pull request #42
Opened 2022-01-31 10:07 UTC by arekkubaczkowski

- [x] Testing
- [x] Automated tests need to be written
- [x]  Doc updates
- [x] Add the resizeMode functionality to the example apps so that customers can try it and our manual QA team can trigger the different resizeModes

QA Criteria: 
 - Playground Example screen presents the video with according configuration options
 - Settings can be found once press the top right corner icon
 - Settings modal presents the list of available configurations along with the `resizeMode` option
 - SDK offers 3 kinds of resize modes: `Aspect Zoom`, `Aspect Fit` and `Aspect Fill` (https://github.com/arekkubaczkowski/amazon-ivs-react-native-player/blob/feat/resize-mode-finishing-up/docs/ivs-player-reference.md#resizemode-optional)
 - Selected option should be applied immediately and visible on video player

https://user-images.githubusercontent.com/18654447/155139507-928e5383-864c-4cb3-a8f4-713e7332a18e.mov

2022-01-31 17:34 UTC, maxstoller commented on docs/ivs-player-reference.md
> +ResizeMode 	aspe`ctZoom 	Fits the parent view ignoring the aspect ratio of the video.
Typo. aspe\`ctZoom => \`aspectZoom\`

Thanks!

2022-02-07 15:43 UTC, alexmdodge commented
@arekkubaczkowski The feature branch has been updated with the original contributors code, good to fix the merge conflicts here and perform final testing 👍

2022-02-09 04:59 UTC, RupamShaw commented
I tried with android its not resizing for aspectFill

2022-02-09 09:54 UTC, RupamShaw commented
i thought like ios if I hard code in android then no need to set in [src/IVSPlayer.tsx] but once i setup this file too all good working

2022-02-22 07:29 UTC, RupamShaw commented
Yeah cant wait release this  resize mode to get release

2022-02-24 21:53 UTC, alexmdodge requested changes
Looks good 👍 One small change which may have been leftover from debugging.

2022-02-24 21:53 UTC, alexmdodge commented on example/src/screens/PlaygroundExample.tsx
> +          volume={0}
Was this added for debugging? Assuming we should revert to the variable?

2022-02-24 22:40 UTC, alexmdodge commented on example/src/screens/PlaygroundExample.tsx
> +          volume={0}
This is a small tweak that I can make on the final feature branch merge 👍

2022-02-24 22:40 UTC, alexmdodge approved these changes

2022-02-24 22:40 UTC, merged